server:
  port: 8989
spring:
  datasource:
    url: jdbc:mysql://81.71.138.54:3306/sg_blog?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    # 文件上传
    multipart:
      # 单个上传文件的最大允许大小
      max-file-size: 20MB
      # HTTP请求中包含的所有文件的总大小的最大允许值
      max-request-size: 20MB
  redis:
    host: 81.71.138.54
    port: 6379

mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

oss:
  accessKey: LH_z5vaM8dK3gsDJ3HyPBhc0YQWXhPNvszCBieis
  secretKey: h6Q8YGZ19Y6xPlA-2lU0MESGNE59Zo2qjc_Hr8xp
  bucket: home-works